### PR TITLE
feat: add `getnf <font-name>` to install specified font

### PR DESCRIPTION
**Pull request by trimclain**
I use automation scripts to bootstrap my system, so I wanted to have something like
`getnf CascadiaCode` to install CascadiaCode Nerd Font.

### CODE REVIEW

**Comment by ronniedroid** [comment]
this has been something I meant to do for some time now as I need it too. 

Thank you, I will test it tomorrow.

**Comment by ronniedroid** [comment]
BTW, want to take over the repo?

**Comment by trimclain** [comment]
Thanks for the offer! I don't mind :smile:

**Comment by ronniedroid** [comment]
Why not put this behind a flag?

Let's say `-d` for example (d for direct) and the font(s) that follow get installed. this will be easier code and also allow multiple font installs in one go.

**Comment by ronniedroid** [comment]
Then it is up to you

Do what you think makes sense 🙂

BTW, I am giving you full rights to this, do as you want, just don't break anything 😄

**Comment by trimclain** [comment]
> BTW, want to take over the repo?

By the way, I wanted to suggest transfering this project to an organization similar to how Chris did it with [Zap](https://github.com/zap-zsh/zap) and [LunarVim](https://github.com/LunarVim/LunarVim)

**Comment by ronniedroid** [comment]
> And have you tested this? Does it work fine for you in its current state?

I did test it, it does install the font you want, but it doesn't work with the other flags, for example `-k` to keep the zip file.
IMO, this needs to be able to install multiple font while still being able to work with the other flags.

> By the way, I wanted to suggest transfering this project to an organization similar to how Chris did it with [Zap](https://github.com/zap-zsh/zap) and [LunarVim](https://github.com/LunarVim/LunarVim)

If it worth it? It is a very simple and small project.

**Comment by trimclain** [comment]
> I did test it, it does install the font you want, but it doesn't work with the other flags, for example `-k` to keep the zip file. IMO, this needs to be able to install multiple font while still being able to work with the other flags.
>
Sure, I'll work on it

> If it worth it? It is a very simple and small project.
>
I could also see a room for it growing 😄 And Zap is also pretty small. 
But no problem, that's your call

**Pull request merged**
